#!/bin/bash

USAGE="Usage: delete-client <client name>"

client_name=$1

[[ -n "$client_name" ]] || { echo $USAGE; exit 0 ; }

export EASY_RSA="/etc/openvpn/easy-rsa"
export OPENSSL="openssl"
export PKCS11TOOL="pkcs11-tool"
export GREP="grep"
export KEY_CONFIG="`/etc/openvpn/easy-rsa/whichopensslcnf /etc/openvpn/easy-rsa`"
export KEY_DIR="/etc/openvpn/easy-rsa/keys"
export PKCS11_MODULE_PATH="dummy"
export PKCS11_PIN="dummy"
export KEY_SIZE=1024
export CA_EXPIRE=3650
export KEY_EXPIRE=3650
export KEY_COUNTRY="RU"
export KEY_PROVINCE="MO"
export KEY_CITY="Moscow"
export KEY_ORG="Destiny Development"
export KEY_EMAIL="admin@ddestiny.ru"

cd /etc/openvpn/easy-rsa
./revoke-full $client_name
cd keys
cp crl.pem /etc/openvpn/keys/

rm -rf /etc/openvpn/ccd/$client_name
rm -rf /etc/openvpn/keys/client/$client_name.*

exit 0
