---

all:
  vars:
    change_repo_list:                  'true'
    repo_rhel_extras:                  false
    repo_rhel_optional:                false
    repo_rhel_ansible_26:              false
    repo_pgdg_bdr_94:                  false
    repo_pgee_96:                      false
    repo_pgpro_std_966:                false
    repo_pgpro_std_96_lt:              false
    repo_pgdg_94:                      false
    repo_pgdg_95:                      false
    repo_mongo_34:                     false
    repo_mongo_36:                     false
    repo_mongo_40:                     false
    change_zabbix_agentd:              'true'
    change_resolv:                     'true'
  children:
    MSK:                                # AREA Moscow
      vars:
        cod_ou:                         UN1
      children:
        MSK_inside:                     # Segment inside
          vars:
            segment:                    'inside'
            realm:                      ''
            work_group:                 'DPC'
            sudo_server:                'ldap:// ldap://'
            mirror_server:              '10.'
            name_server:                ['8', '19', '129', '138']
            zbx_active:                  '16'
            zbx_passive:                 '14,15'
            sys_ou:                    'System'
          children:
            MSK_inside_test:
              hosts:
                n76:
                n5:
            MSK_inside_LDAP:
              hosts:
                n0:
                  ansible_host:         '1'
                  vars:
                    id:                 '2'
                n71:
                  ansible_host:         '104'
                  vars:
                    id:                 '11'
            MSK_inside_REPO:
              vars:
                change_repo_list:       'false'
              hosts:
                аооо:
                  ansible_host:         '107'
            MSK_inside_UAIS:            # Zabbix servers
              vars:
                change_zabbix_agentd    'false'
              hosts:
                n774
                n776
                n742
                n743
                n748
                n751
          hosts:
            n15:
              repo_pgee_96:           true
            n76:
            n78:
            n77:
            n76:
            n79:
            n70:
            n71:
            n72:
            n73:
            n73:
            n74:
            n75:
            n76:
            n76:
              repo_pgpro_std_966:     true
            n75:
              repo_pgpro_std_96_lt:   true
            n78:
            n79:
            n72:
            n73:
        MSK_rDMZ:                       # Segment rDMZ
          vars:
            segment:                    'rDMZ'
            realm:                      'DU'
            work_group:                 'D'
            sudo_server:                'ldap://1 ldap://1'
            mirror_server:              'http://1'
            name_server:                ['', '19', '19', '18']
            zbx_active:                  '108'
            zbx_passive:                 '10.15,16'
            sys_ou:                     'System'
          children:
            MSK_rDMZ_LDAP:
              hosts:
                n7701-sys402:
                  ansible_host:         '14'
                  vars:
                    id:                 '5'
                n73:
                  ansible_host:         '105'
                  vars:
                    id:                 '14'
            MSK_rDMZ_REPO:
              vars:
                change_repo_list:       'false'
              hosts:
                n7:
                  ansible_host:         '110'
            MSK_rDMZ_UAIS:              # Zabbix servers UAIS (Harchenkov A.)
              vars:
                change_zabbix_agentd    'false'
              hosts:

          #hosts:
        MSK_iDMZ:                       # Segment iDMZ
          vars:
            segment:                    'iDMZ'
            realm:                      'I'
            work_group:                 'IDMZ'
            sudo_server:                'ldap://10 ldap://10'
            mirror_server:              'http://10'
            name_server:                ['10', '10']
            zbx_active:                  '16'
            zbx_passive:                 '1041,12'
            sys_ou:                    'System'
          children:
            MSK_iDMZ_LDAP:
              hosts:
                n74:
                  ansible_host:         '14'
                  vars:
                    id:                 '8'
                n5:
                  ansible_host:         '1015'
                  vars:
                    id:                 '17'
            MSK_iDMZ_REPO:
              vars:
                change_repo_list:       'false'
              hosts:
                n:
                  ansible_host:         '196'
                n70:
                  ansible_host:         '14'
            MSK_iDMZ_UAIS:              # Zabbix servers UAIS (Harchenkov A.)
              vars:
                change_zabbix_agentd    'false'
              hosts:
                n75
                n76
          hosts:
            n248:
            n247:
            n246:
            n245:
            n244:
            n331:
            n330:
            n333:
            n332:

local_mirrors:
  children:
    MSK_inside_REPO:
    MSK_rDMZ_REPO:
    MSK_iDMZ_REPO:
    DBN_inside_REPO:
    DBN_rDMZ_REPO:
    DBN_iDMZ_REPO:
    GOR_inside_REPO:
    GOR_rDMZ_REPO:
    GOR_iDMZ_REPO:
