---

- name: Populate service facts
  service_facts:

#- debug:
#    var: ansible_facts.services

- name: Disable default services (systemd)
  systemd:
    name: '{{ item }}'
    state: 'stopped'
    enabled: 'no'
    masked: 'yes'
  with_items:
    - firewalld
    - NetworkManager

#- name: Disable default services (systemd)
#  systemd:
#    name: '{{ item }}'
#    masked: 'yes'
#  with_items:
#    - iptables
#    - ip6tables

- name: Disable SELinux (systemd)
  selinux:
    state: 'disabled'

- name: Enable network (systemd)
  service:
    name: network
    enabled: yes
    state: started

