---

- name: Restarting ad services
  service: 
    name: '{{ item }}'
    state: started
    enabled: yes
  with_items:
    - winbind
    - oddjobd

- name: Restarting ad services ALT
  service: 
    name: '{{ item }}'
    state: started
    enabled: yes
  with_items:
    - winbind
