---

- name: Basic settings
  template:
     src: "zabbix_agentd.conf.j2"
     dest: "/etc/zabbix/zabbix_agentd.conf"
     owner: "root"
     group: "root"
     mode: "0644"
  notify: Restarting zabbix-agent
